name: NoPhantomSleep
version: '${version}'
main: org.skydom.chosen.server.nophantomsleep.NoPhantomSleep
api-version: 1.20
authors: [Chosen_1st]
commands:
  clearsleepplayer:
    description: Clear sleeping players
    usage: /clearsleepplayer
    permission: NoPhantomSleep.clearsleepplayer
    default: op